import {
  IoFastFoodOutline,
  IoCarOutline,
  IoFilmOutline,
  IoReceiptOutline,
  IoBagHandleOutline,
  IoFitnessOutline,
  IoSchoolOutline,
  IoAirplaneOutline,
  IoCartOutline,
  IoPhonePortraitOutline,
  IoHeartOutline,
  IoPeopleOutline,
  IoBriefcaseOutline,
  IoLaptopOutline,
  IoTrendingUpOutline,
  IoGiftOutline,
  IoCashOutline,
  IoStatsChartOutline,
  IoHomeOutline,
  IoReturnDownBackOutline,
} from "react-icons/io5";

export const categories = {
income: [
  {
    value: "salary",
    label: "Salary",
    color: "from-emerald-400 to-emerald-500",
    icon: IoBriefcaseOutline,
    bgColor: "bg-emerald-50",
  },
  {
    value: "freelance",
    label: "Freelance",
    color: "from-blue-400 to-blue-500",
    icon: IoLaptopOutline,
    bgColor: "bg-blue-50",
  },
  {
    value: "investment",
    label: "Investment",
    color: "from-purple-400 to-purple-500",
    icon: IoTrendingUpOutline,
    bgColor: "bg-purple-50",
  },
  {
    value: "gift",
    label: "Gift",
    color: "from-pink-400 to-pink-500",
    icon: IoGiftOutline,
    bgColor: "bg-pink-50",
  },
  {
    value: "bonus",
    label: "Bonus",
    color: "from-amber-400 to-amber-500",
    icon: IoCashOutline,
    bgColor: "bg-amber-50",
  },
  {
    value: "dividend",
    label: "Dividend",
    color: "from-cyan-400 to-cyan-500",
    icon: IoStatsChartOutline,
    bgColor: "bg-cyan-50",
  },
  {
    value: "rental",
    label: "Rental Income",
    color: "from-indigo-400 to-indigo-500",
    icon: IoHomeOutline,
    bgColor: "bg-indigo-50",
  },
  {
    value: "refund",
    label: "Refund",
    color: "from-lime-400 to-lime-500",
    icon: IoReturnDownBackOutline,
    bgColor: "bg-lime-50",
  },
],


  expense: [
    {
      value: "food",
      label: "Food & Dining",
      color: "from-red-400 to-red-500",
      icon: IoFastFoodOutline,
      bgColor: "bg-red-50",
    },
    {
      value: "transport",
      label: "Transport",
      color: "from-orange-400 to-orange-500",
      icon: IoCarOutline,
      bgColor: "bg-orange-50",
    },
    {
      value: "entertainment",
      label: "Entertainment",
      color: "from-pink-400 to-pink-500",
      icon: IoFilmOutline,
      bgColor: "bg-pink-50",
    },
    {
      value: "bills",
      label: "Bills & Utilities",
      color: "from-yellow-400 to-yellow-500",
      icon: IoReceiptOutline,
      bgColor: "bg-yellow-50",
    },
    {
      value: "shopping",
      label: "Shopping",
      color: "from-indigo-400 to-indigo-500",
      icon: IoBagHandleOutline,
      bgColor: "bg-indigo-50",
    },
    {
      value: "health",
      label: "Health & Fitness",
      color: "from-teal-400 to-teal-500",
      icon: IoFitnessOutline,
      bgColor: "bg-teal-50",
    },
    {
      value: "education",
      label: "Education",
      color: "from-cyan-400 to-cyan-500",
      icon: IoSchoolOutline,
      bgColor: "bg-cyan-50",
    },
    {
      value: "travel",
      label: "Travel",
      color: "from-violet-400 to-violet-500",
      icon: IoAirplaneOutline,
      bgColor: "bg-violet-50",
    },
    {
      value: "groceries",
      label: "Groceries",
      color: "from-lime-400 to-lime-500",
      icon: IoCartOutline,
      bgColor: "bg-lime-50",
    },
    {
      value: "subscription",
      label: "Subscriptions",
      color: "from-rose-400 to-rose-500",
      icon: IoPhonePortraitOutline,
      bgColor: "bg-rose-50",
    },
    {
      value: "personal",
      label: "Personal Care",
      color: "from-amber-400 to-amber-500",
      icon: IoHeartOutline,
      bgColor: "bg-amber-50",
    },
    {
      value: "charity",
      label: "Charity",
      color: "from-purple-400 to-purple-500",
      icon: IoPeopleOutline,
      bgColor: "bg-purple-50",
    },
  ],
};
